version: '3.3'
services:

  frontend:
    container_name: foodgram_frontend
    image: xanhex/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  postgres_db:
    container_name: foodgram_database
    image: postgres:13.10
    restart: always
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    container_name: foodgram_backend
    image: xanhex/foodgram_backend:latest
    build: ../backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    env_file:
      - ../.env
    depends_on:
      - postgres_db

  nginx:
    container_name: foodgram_gateway
    image: nginx:1.23.3-alpine
    ports:
      - 8000:80
      # - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/etc/nginx/html/static/
      - media:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  database:
  static:
  media: