# Generated by Django 4.2.4 on 2023-08-23 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'избранное',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='ингредиент'
                    ),
                ),
                (
                    'measurement_unit',
                    models.CharField(
                        max_length=200, verbose_name='единицы измерения'
                    ),
                ),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, 'Минимум 1 ингредиент'
                            )
                        ],
                        verbose_name='колличество',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ингредиенты в рецепте',
                'verbose_name_plural': 'ингредиенты в рецептах',
                'ordering': ('recipe',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, verbose_name='название блюда'
                    ),
                ),
                ('text', models.TextField(verbose_name='описание')),
                (
                    'pub_date',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='дата публикации'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='recipes/', verbose_name='изображение блюда'
                    ),
                ),
                (
                    'cooking_time',
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, 'Минимальное время приготовления: 1 мин'
                            )
                        ]
                    ),
                ),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=200, unique=True, verbose_name='тег'
                    ),
                ),
                (
                    'color',
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Невалидный HEX-код',
                                regex='^\\#[a-zA-Z0-9]{6}$',
                            )
                        ],
                        verbose_name='цвет',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Не соответствует формату [a-zA-Z0-9_-]',
                                regex='^[-a-zA-Z0-9_]+$',
                            )
                        ],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(
                fields=('name', 'color', 'slug'),
                name='recipes_tag_unique_for_tag',
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(
                check=models.Q(('name__length__gt', 0)),
                name='recipes_tag_name_empty',
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(
                check=models.Q(('color__length__gt', 0)),
                name='recipes_tag_color_empty',
            ),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.CheckConstraint(
                check=models.Q(('slug__length__gt', 0)),
                name='recipes_tag_slug_empty',
            ),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cart_recipe',
                to='recipes.recipe',
                verbose_name='рецепт в корзине',
            ),
        ),
    ]
