# Generated by Django 4.2.4 on 2023-08-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                blank=True,
                default='recipes/default.png',
                upload_to='recipes/',
                verbose_name='изображение блюда',
            ),
        ),
    ]
